GET http://localhost:3000/courses


###########
GET http://localhost:3000/courses/66ad4f2a60c4ebd1a5c2c526


###############

POST http://localhost:3000/courses
Content-Type: application/json

{
    "courseCode": "CSCI 3130",
    "courseDescription": "Software Engineering",
    "year": 3,
    "bcsRequirement": true,
    "bacsRequirement": true,
    "coopRequirement": false,
    "prerequisites": ["66d518f7c095ca8794743203", "66d51912c095ca87947434e8"]
}

############## update course:
PUT http://localhost:3000/courses/66d51af1c095ca8794746783
Content-Type: application/json

{
   
}

##########
DELETE http://localhost:3000/courses/xxxx

##### delete all
GET http://localhost:3000/courses/nuke