GET http://localhost:3000/courses


###########
GET http://localhost:3000/courses/66ad4f2a60c4ebd1a5c2c526


###############

POST http://localhost:3000/courses
Content-Type: application/json

{
    "courseCode": "CSCI 0001",
    "courseDescription": "intro to everything"
}

##############
POST http://localhost:3000/courses
Content-Type: application/json

{
    "courseCode": "CSCI 0010",
    "courseDescription": "sequel to everything",
    "prerequisites": ["66ad4f2a60c4ebd1a5c2c526"]
}

##############
PUT http://localhost:3000/courses/66ad4f2a60c4ebd1a5c2c526
Content-Type: application/json

{
    "courseCode": "CSCI 0001",
    "courseDescription": "testingUpdate",
    "prerequisites": []
}

##########
DELETE http://localhost:3000/courses/xxxx

##### delete all
GET http://localhost:3000/courses/nuke