GET http://localhost:3000/reviews


###########
GET http://localhost:3000/reviews/66aa7cb014b0439947139b25

##############
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "content": "second review to test average calc",
    "quality": 4,
    "difficulty": 5,
    "courseLoad": 4,
    "courseId": "66b7c04129a4eda3a8089e07",
    "author": "66aa8d188aaa8b508892e746"
}

##############
PUT http://localhost:3000/reviews/66b10940f72c890e0f3b7b9e
Content-Type: application/json

{
    "content": "updated the review",
}

##########
DELETE http://localhost:3000/reviews/66b1649408980f3eddf2c6de


######
//review for 2nd course
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "content": "adding 2nd review to break the tie :)",
    "quality": 4,
    "difficulty": 4,
    "courseLoad": 4,
    "courseId": "66ad4f3160c4ebd1a5c2c528",
    "author": "66aa8d188aaa8b508892e746"
}
