GET http://localhost:3000/reviews


###########
GET http://localhost:3000/reviews/66aa7cb014b0439947139b25

##############
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "content": "adding to 2nd course",
    "quality": 4,
    "difficulty": 4,
    "courseLoad": 4,
    "courseId": "66aa7319bdf507873c1cce4f",
    "author": "66aa8d188aaa8b508892e746"
}

##############
PUT http://localhost:3000/reviews/6678692e9bacf2d29119253d
Content-Type: application/json

{
    "content": "updated before deleting...",
    "quality": 4,
    "difficulty": 1,
    "courseLoad": 1,
    "courseId": "6678688d84325796311b3691"
}

##########
DELETE http://localhost:3000/reviews/66ac0f6b2c66d4ed59b9e74a