GET http://localhost:3000/users

################

GET http://localhost:3000/users/66aa8d188aaa8b508892e746



###############

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "sudo",
    "password": "password"
}


#############

PUT http://localhost:3000/users/66aa8d188aaa8b508892e746
Content-Type: application/json

{
    "username": "sudo"
}